CREATE DATABASE CONTA_CORRENTE;
GO

USE CONTA_CORRENTE;
GO

CREATE TABLE AGENCIAS (
    NUM_AGE     NUMERIC(5,0) PRIMARY KEY NOT NULL,
    NOME        VARCHAR(60) NOT NULL,
    ENDERECO    VARCHAR(100) NOT NULL,
    NUMERO      VARCHAR(8) NOT NULL,
    COMPLEMENTO VARCHAR(40) NOT NULL,
    BAIRRO      VARCHAR(50) NOT NULL,
    CIDADE      VARCHAR(50) NOT NULL,
    UF          CHAR(2)     NOT NULL,
    CEP         CHAR(8)     NOT NULL,
    TELEFONE    VARCHAR(15) NOT NULL
);
GO

CREATE TABLE CLIENTES (
    ID          NUMERIC(9,0) PRIMARY KEY NOT NULL,
    NOME        VARCHAR(80) NOT NULL,
    ENDERECO    VARCHAR(100) NOT NULL,
    NUMERO      VARCHAR(8)  NOT NULL,
    COMPLEMENTO VARCHAR(40) NOT NULL,
    BAIRRO      VARCHAR(50) NOT NULL,
    CIDADE      VARCHAR(50) NOT NULL,
    UF          CHAR(2)     NOT NULL,
    CEP         CHAR(8)     NOT NULL,
    TELEFONE    VARCHAR(15) NOT NULL,
    CPF         CHAR(11)    NOT NULL,
    DATA_NASC   DATETIME    NOT NULL,
    CNPJ        CHAR(14)    NOT NULL,
    EMAIL       VARCHAR(30) NOT NULL,
    SEXO        CHAR(2)     NOT NULL
);
GO

CREATE TABLE HISTORICOS (
    ID          NUMERIC(4,0) PRIMARY KEY NOT NULL,
    DESCRICAO   VARCHAR(150) NOT NULL
);
GO

CREATE TABLE CONTACORRENTE (
    NUM_AGE     NUMERIC(5,0) NOT NULL,
    NUM_CC      NUMERIC(10,0) NOT NULL,
    ID_CLIENTE  NUMERIC(9,0) NOT NULL,
    SALDO       NUMERIC(15,2) NOT NULL,
    PRIMARY KEY (NUM_AGE, NUM_CC),
    CONSTRAINT FK_CONTACORRENTE_AGE FOREIGN KEY (NUM_AGE) REFERENCES AGENCIAS(NUM_AGE),
    CONSTRAINT FK_CONTACORRENTE_CLI FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);
GO

CREATE TABLE USUARIOS (
    ID          VARCHAR(20) PRIMARY KEY NOT NULL,
    SENHA       VARCHAR(20) NOT NULL,
    NUM_AGE     NUMERIC(5,0) NOT NULL,
    NUM_CC      NUMERIC(10,0) NOT NULL,
    CONSTRAINT FK_USUARIOS_CC FOREIGN KEY (NUM_AGE, NUM_CC)
        REFERENCES CONTACORRENTE(NUM_AGE, NUM_CC)
);
GO

CREATE TABLE MOVIMENTACAO (
    NUM_AGE         NUMERIC(5,0) NOT NULL,
    NUM_CC          NUMERIC(10,0) NOT NULL,
    DATA_MOV        DATETIME     NOT NULL,
    NUM_DOCTO       VARCHAR(6)   NOT NULL,
    DEBITO_CREDITO  CHAR(1)      NOT NULL,
    ID_HISTORICO    NUMERIC(4,0) NOT NULL,
    COMPLEMENTO_HIS VARCHAR(150) NOT NULL,
    VALOR           NUMERIC(9,2) NOT NULL,
    SALDO           NUMERIC(15,2) NOT NULL,
    PRIMARY KEY (NUM_AGE, NUM_CC, DATA_MOV, NUM_DOCTO),
    CONSTRAINT FK_MOV_AGE FOREIGN KEY (NUM_AGE)
        REFERENCES AGENCIAS(NUM_AGE),
    CONSTRAINT FK_MOV_CC FOREIGN KEY (NUM_AGE, NUM_CC)
        REFERENCES CONTACORRENTE(NUM_AGE, NUM_CC),
    CONSTRAINT FK_MOV_HIS FOREIGN KEY (ID_HISTORICO)
        REFERENCES HISTORICOS(ID)
);
