/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CLASSES.ExtratoMovimentacao;
import DAO.ExtratoMovimentacaoDAO;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 * @author Ryan Carlo Negretti Pereira
 */
public class ViewExtratoMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form ExtratoMovimentacao
     */
    public ViewExtratoMovimentacao() {
        initComponents();
    }

    String operacaoAtivaGlobal = "NENHUM";

    private void camposOB() {
        jLabelNumeroDocumento.setVisible(true);
        jTextFieldNumeroDocumento.setVisible(true);
    }

    private void limparCampos() {
        jTextFieldNumeroConta.setText(" ");
        jTextFieldNumeroAgencia.setText(" ");
        jTextFieldNumeroDocumento.setText(" ");
        jTextFieldDataMovimentacao.setText(" ");
        jTextFieldIdHistorico.setText(" ");
        jTextFieldComplementoHistorico.setText(" ");
        jTextFieldValor.setText(" ");
        jTextFieldSaldo.setText(" ");

        jComboBoxCartaoDC.setSelectedIndex(0);
    }

    private void camposON() {
        jLabelNumeroConta.setVisible(true);
        jLabelNumeroAgencia.setVisible(true);
        jLabelDataMovimentacao.setVisible(true);
        jLabelCartaoDC.setVisible(true);
        jLabelIdHistorico.setVisible(true);
        jLabelComplementoHistorico.setVisible(true);
        jLabelValor.setVisible(true);
        jLabelSaldo.setVisible(true);

        jTextFieldNumeroConta.setVisible(true);
        jTextFieldNumeroAgencia.setVisible(true);
        jTextFieldDataMovimentacao.setVisible(true);
        jTextFieldIdHistorico.setVisible(true);
        jTextFieldComplementoHistorico.setVisible(true);
        jTextFieldValor.setVisible(true);
        jTextFieldSaldo.setVisible(true);

        jComboBoxCartaoDC.setVisible(true);
    }

    private void camposOFF() {
        jLabelNumeroConta.setVisible(false);
        jLabelNumeroAgencia.setVisible(false);
        jLabelDataMovimentacao.setVisible(false);
        jLabelCartaoDC.setVisible(false);
        jLabelIdHistorico.setVisible(false);
        jLabelComplementoHistorico.setVisible(false);
        jLabelValor.setVisible(false);
        jLabelSaldo.setVisible(false);

        jTextFieldNumeroConta.setVisible(false);
        jTextFieldNumeroAgencia.setVisible(false);
        jTextFieldDataMovimentacao.setVisible(false);
        jTextFieldIdHistorico.setVisible(false);
        jTextFieldComplementoHistorico.setVisible(false);
        jTextFieldValor.setVisible(false);
        jTextFieldSaldo.setVisible(false);

        jComboBoxCartaoDC.setVisible(false);
    }

    public ViewExtratoMovimentacao(String operacaoAtiva) {
        initComponents();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "INCLUIR";
        if (operacaoAtiva.equals(operacao)) {
            camposOB();
            camposON();
            jButtonCadastrar.setVisible(true);
            jButtonLimpar.setVisible(true);
            jButtonExcluir.setVisible(false);
            jButtonConsultar.setVisible(false);
            jButtonAlterar.setVisible(false);
        }
        operacao = "PesquisarAlterar";
        if (operacaoAtiva.equals(operacao)) {
            camposOB();
            camposOFF();
            jButtonCadastrar.setVisible(false);
            jButtonLimpar.setVisible(true);
            jButtonExcluir.setVisible(false);
            jButtonConsultar.setVisible(true);
            jButtonAlterar.setVisible(false);
        }
        operacao = "PesquisarExcluir";
        if (operacaoAtiva.equals(operacao)) {
            camposOB();
            camposOFF();
            jButtonCadastrar.setVisible(false);
            jButtonLimpar.setVisible(true);
            jButtonExcluir.setVisible(false);
            jButtonConsultar.setVisible(true);
            jButtonAlterar.setVisible(false);
        }
    }

    ExtratoMovimentacao extrato_movimentacao_tela = new ExtratoMovimentacao();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumeroConta = new javax.swing.JLabel();
        jTextFieldNumeroConta = new javax.swing.JTextField();
        jLabelNumeroAgencia = new javax.swing.JLabel();
        jLabelNumeroDocumento = new javax.swing.JLabel();
        jTextFieldNumeroAgencia = new javax.swing.JTextField();
        jTextFieldNumeroDocumento = new javax.swing.JTextField();
        jTextFieldDataMovimentacao = new javax.swing.JTextField();
        jLabelDataMovimentacao = new javax.swing.JLabel();
        jLabelCartaoDC = new javax.swing.JLabel();
        jTextFieldIdHistorico = new javax.swing.JTextField();
        jLabelIdHistorico = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldSaldo = new javax.swing.JTextField();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelComplementoHistorico = new javax.swing.JLabel();
        jTextFieldComplementoHistorico = new javax.swing.JTextField();
        jComboBoxCartaoDC = new javax.swing.JComboBox<>();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNumeroConta.setText("NUMERO DA CONTA:");

        jTextFieldNumeroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroContaActionPerformed(evt);
            }
        });

        jLabelNumeroAgencia.setText("NUMERO DA AGENCIA:");

        jLabelNumeroDocumento.setText("NUMERO DO DOCUMENTO:");

        jTextFieldNumeroAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroAgenciaActionPerformed(evt);
            }
        });

        jTextFieldNumeroDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroDocumentoActionPerformed(evt);
            }
        });

        jTextFieldDataMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataMovimentacaoActionPerformed(evt);
            }
        });

        jLabelDataMovimentacao.setText("DATA MOVIMENTAÇÃO:");

        jLabelCartaoDC.setText("CARTAO D / C:");

        jTextFieldIdHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdHistoricoActionPerformed(evt);
            }
        });

        jLabelIdHistorico.setText("ID DO HISTORICO:");

        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });

        jLabelValor.setText("VALOR:");

        jTextFieldSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaldoActionPerformed(evt);
            }
        });

        jLabelSaldo.setText("SALDO:");

        jLabelComplementoHistorico.setText("COMPLEMENTO DO HISTORICO:");

        jTextFieldComplementoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldComplementoHistoricoActionPerformed(evt);
            }
        });

        jComboBoxCartaoDC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Selecionar -", "D", "C" }));

        jButtonCadastrar.setText("CADASTRAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("LIMPAR");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("CONSULTAR");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelDataMovimentacao)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelCartaoDC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCartaoDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelValor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelSaldo)
                                        .addGap(3, 3, 3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldValor)
                                    .addComponent(jTextFieldSaldo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jTextFieldDataMovimentacao)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelComplementoHistorico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldComplementoHistorico)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNumeroAgencia)
                            .addComponent(jLabelNumeroConta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumeroConta)
                            .addComponent(jTextFieldNumeroAgencia))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNumeroDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNumeroDocumento)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIdHistorico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdHistorico)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAlterar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroConta)
                    .addComponent(jTextFieldNumeroConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroAgencia)
                    .addComponent(jTextFieldNumeroAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumeroDocumento)
                    .addComponent(jTextFieldNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataMovimentacao)
                    .addComponent(jTextFieldDataMovimentacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCartaoDC)
                    .addComponent(jComboBoxCartaoDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdHistorico)
                    .addComponent(jTextFieldIdHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComplementoHistorico)
                    .addComponent(jTextFieldComplementoHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValor)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSaldo)
                    .addComponent(jTextFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAlterar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumeroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroContaActionPerformed

    private void jTextFieldNumeroAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroAgenciaActionPerformed

    private void jTextFieldNumeroDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroDocumentoActionPerformed

    private void jTextFieldDataMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataMovimentacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataMovimentacaoActionPerformed

    private void jTextFieldIdHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdHistoricoActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jTextFieldSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSaldoActionPerformed

    private void jTextFieldComplementoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldComplementoHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldComplementoHistoricoActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        //CADASTRAR DADOS
        String operacao = "INCLUIR";
        if (operacaoAtivaGlobal.equals(operacao)) {
            ExtratoMovimentacao dados_extrato_movimentacao = new ExtratoMovimentacao();

            dados_extrato_movimentacao.setNum_cc(Long.parseLong(jTextFieldNumeroConta.getText()));
            dados_extrato_movimentacao.setNum_age(Integer.parseInt(jTextFieldNumeroAgencia.getText()));
            dados_extrato_movimentacao.setNum_docto(jTextFieldNumeroDocumento.getText());
            String data = jTextFieldDataMovimentacao.getText();
            LocalDateTime dataMov = LocalDateTime.parse(data);
            dados_extrato_movimentacao.setData_mov(dataMov);
            dados_extrato_movimentacao.setDebito_credito(jComboBoxCartaoDC.getSelectedItem().toString());
            dados_extrato_movimentacao.setId_his(Integer.parseInt(jTextFieldIdHistorico.getText()));
            dados_extrato_movimentacao.setCompl_his(jTextFieldComplementoHistorico.getText());
            dados_extrato_movimentacao.setValor(Double.parseDouble(jTextFieldValor.getText()));
            dados_extrato_movimentacao.setSaldo(Double.parseDouble(jTextFieldSaldo.getText()));

            ExtratoMovimentacaoDAO objcon = new ExtratoMovimentacaoDAO();

            objcon.insereRegistroJFBD("MOVIMENTACAO", dados_extrato_movimentacao.dadosSQLValues());

            limparCampos();
            dispose();
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        //LIMPAR TELA
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        //BUSCAR DADOS
        String operacao = "PesquisarAlterar";
        if (operacaoAtivaGlobal.equals((operacao))) {
            ExtratoMovimentacaoDAO objcon = new ExtratoMovimentacaoDAO();
            ExtratoMovimentacao dados_extrato_movimentacao;
            dados_extrato_movimentacao = objcon.pesquisaRegistroJFDB("MOVIMENTACAO", "NUM_DOCTO = '"
                    + jTextFieldNumeroDocumento.getText() + "'");

            if (dados_extrato_movimentacao != null) {
                // Preencher os campos da tela com os dados do cliente
                jTextFieldNumeroConta.setText(String.valueOf(dados_extrato_movimentacao.getNum_cc()));
                jTextFieldNumeroAgencia.setText(String.valueOf(dados_extrato_movimentacao.getNum_age()));
                jTextFieldNumeroDocumento.setText(dados_extrato_movimentacao.getNum_docto());
                LocalDateTime dataMov = dados_extrato_movimentacao.getData_mov();
                jTextFieldDataMovimentacao.setText(dataMov.toString());
                jComboBoxCartaoDC.setSelectedItem(dados_extrato_movimentacao.getDebito_credito().trim().toUpperCase());
                jTextFieldIdHistorico.setText(String.valueOf(dados_extrato_movimentacao.getId_his()));
                jTextFieldComplementoHistorico.setText(dados_extrato_movimentacao.getCompl_his());
                jTextFieldValor.setText(String.valueOf(dados_extrato_movimentacao.getValor()));
                jTextFieldSaldo.setText(String.valueOf(dados_extrato_movimentacao.getSaldo()));

                camposON();
                jButtonCadastrar.setVisible(false);
                jButtonLimpar.setVisible(true);
                jButtonExcluir.setVisible(false);
                jButtonConsultar.setVisible(true);
                jButtonAlterar.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Extrato de Movimentacao não encontrado.");
            }
        }
        operacao = "PesquisarExcluir";
        if (operacaoAtivaGlobal.equals((operacao))) {
            ExtratoMovimentacaoDAO objcon = new ExtratoMovimentacaoDAO();
            ExtratoMovimentacao dados_extrato_movimentacao;
            dados_extrato_movimentacao = objcon.pesquisaRegistroJFDB("MOVIMENTACAO", "NUM_DOCTO = '"
                    + jTextFieldNumeroDocumento.getText() + "'");

            if (dados_extrato_movimentacao != null) {
                // Preencher os campos da tela com os dados do cliente
                jTextFieldNumeroConta.setText(String.valueOf(dados_extrato_movimentacao.getNum_cc()));
                jTextFieldNumeroAgencia.setText(String.valueOf(dados_extrato_movimentacao.getNum_age()));
                jTextFieldNumeroDocumento.setText(dados_extrato_movimentacao.getNum_docto());
                LocalDateTime dataMov = dados_extrato_movimentacao.getData_mov();
                jTextFieldDataMovimentacao.setText(dataMov.toString());
                jComboBoxCartaoDC.setSelectedItem(dados_extrato_movimentacao.getDebito_credito().trim().toUpperCase());
                jTextFieldIdHistorico.setText(String.valueOf(dados_extrato_movimentacao.getId_his()));
                jTextFieldComplementoHistorico.setText(dados_extrato_movimentacao.getCompl_his());
                jTextFieldValor.setText(String.valueOf(dados_extrato_movimentacao.getValor()));
                jTextFieldSaldo.setText(String.valueOf(dados_extrato_movimentacao.getSaldo()));

                camposON();
                jButtonCadastrar.setVisible(false);
                jButtonLimpar.setVisible(true);
                jButtonExcluir.setVisible(true);
                jButtonConsultar.setVisible(true);
                jButtonAlterar.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Extrato de Movimentacao não encontrado.");
            }
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // EXCLUIR
        ExtratoMovimentacaoDAO objcon = new ExtratoMovimentacaoDAO();
        ExtratoMovimentacao dados_extrato_movimentacao;
        dados_extrato_movimentacao = objcon.pesquisaRegistroJFDB("MOVIMENTACAO", "NUM_DOCTO = '"
                + jTextFieldNumeroDocumento.getText() + "'");

        jTextFieldNumeroConta.setText(String.valueOf(dados_extrato_movimentacao.getNum_cc()));
        jTextFieldNumeroAgencia.setText(String.valueOf(dados_extrato_movimentacao.getNum_age()));
        jTextFieldNumeroDocumento.setText(dados_extrato_movimentacao.getNum_docto());
        LocalDateTime dataMov = dados_extrato_movimentacao.getData_mov();
        jTextFieldDataMovimentacao.setText(dataMov.toString());
        jComboBoxCartaoDC.setSelectedItem(dados_extrato_movimentacao.getDebito_credito().trim().toUpperCase());
        jTextFieldIdHistorico.setText(String.valueOf(dados_extrato_movimentacao.getId_his()));
        jTextFieldComplementoHistorico.setText(dados_extrato_movimentacao.getCompl_his());
        jTextFieldValor.setText(String.valueOf(dados_extrato_movimentacao.getValor()));
        jTextFieldSaldo.setText(String.valueOf(dados_extrato_movimentacao.getSaldo()));

        objcon.excluirRegistroJFDB("MOVIMENTACAO", "NUM_DOCTO = '"
                + jTextFieldNumeroDocumento.getText() + "'");

        limparCampos();
        dispose();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // ALTERAR
        ExtratoMovimentacaoDAO objcon = new ExtratoMovimentacaoDAO();
        ExtratoMovimentacao dados_extrato_movimentacao;
        dados_extrato_movimentacao = objcon.pesquisaRegistroJFDB("MOVIMENTACAO", "NUM_DOCTO = '"
                + jTextFieldNumeroDocumento.getText() + "'");

        dados_extrato_movimentacao.setNum_cc(Long.parseLong(jTextFieldNumeroConta.getText()));
        dados_extrato_movimentacao.setNum_age(Integer.parseInt(jTextFieldNumeroAgencia.getText()));
        dados_extrato_movimentacao.setNum_docto(jTextFieldNumeroDocumento.getText());
        String data = jTextFieldDataMovimentacao.getText();
        LocalDateTime dataMov = LocalDateTime.parse(data);
        dados_extrato_movimentacao.setData_mov(dataMov);
        dados_extrato_movimentacao.setDebito_credito(jComboBoxCartaoDC.getItemAt(WIDTH));
        dados_extrato_movimentacao.setId_his(Integer.parseInt(jTextFieldIdHistorico.getText()));
        dados_extrato_movimentacao.setCompl_his(jTextFieldComplementoHistorico.getText());
        dados_extrato_movimentacao.setValor(Double.parseDouble(jTextFieldValor.getText()));
        dados_extrato_movimentacao.setSaldo(Double.parseDouble(jTextFieldSaldo.getText()));

        try {
            objcon.alteraRegistroJFDB("MOVIMENTACAO", dados_extrato_movimentacao.alteraDadosSQLValues(),
                    "NUM_DOCTO ='" + jTextFieldNumeroDocumento.getText() + "'");
            limparCampos();
            dispose();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Não foi possível alterar. erro: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewExtratoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewExtratoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewExtratoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewExtratoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewExtratoMovimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JComboBox<String> jComboBoxCartaoDC;
    private javax.swing.JLabel jLabelCartaoDC;
    private javax.swing.JLabel jLabelComplementoHistorico;
    private javax.swing.JLabel jLabelDataMovimentacao;
    private javax.swing.JLabel jLabelIdHistorico;
    private javax.swing.JLabel jLabelNumeroAgencia;
    private javax.swing.JLabel jLabelNumeroConta;
    private javax.swing.JLabel jLabelNumeroDocumento;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JTextField jTextFieldComplementoHistorico;
    private javax.swing.JTextField jTextFieldDataMovimentacao;
    private javax.swing.JTextField jTextFieldIdHistorico;
    private javax.swing.JTextField jTextFieldNumeroAgencia;
    private javax.swing.JTextField jTextFieldNumeroConta;
    private javax.swing.JTextField jTextFieldNumeroDocumento;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
