/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

/**
 * @author Ryan Carlo Negretti Pereira
 */
public class ViewMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public ViewMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAgenciasIncluir = new javax.swing.JMenuItem();
        jMenuAgenciasAlterar = new javax.swing.JMenuItem();
        jMenuAgenciasExcluir = new javax.swing.JMenuItem();
        jMenuAgenciasConsultar = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        jMenuClientesIncluir = new javax.swing.JMenuItem();
        jMenuClientesAlterar = new javax.swing.JMenuItem();
        jMenuClientesExcluir = new javax.swing.JMenuItem();
        jMenuClientesConsultar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuContaCorrenteIncluir = new javax.swing.JMenuItem();
        jMenuContaCorrenteAlterar = new javax.swing.JMenuItem();
        jMenuContaCorrenteExcluir = new javax.swing.JMenuItem();
        jMenuContaCorrenteConsultar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuHistoricoIncluir = new javax.swing.JMenuItem();
        jMenuHistoricoAlterar = new javax.swing.JMenuItem();
        jMenuHistoricoExcluir = new javax.swing.JMenuItem();
        jMenuHistoricoConsultar = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuUsuariosIncluir = new javax.swing.JMenuItem();
        jMenuUsuariosAlterar = new javax.swing.JMenuItem();
        jMenuUsuariosExcluir = new javax.swing.JMenuItem();
        jMenuUsuariosConsultar = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuExtratoMovimentacaoIncluir = new javax.swing.JMenuItem();
        jMenuExtratoMovimentacaoAlterar = new javax.swing.JMenuItem();
        jMenuExtratoMovimentacaoExcluir = new javax.swing.JMenuItem();
        jMenuExtratoMovimentacaoConsultar = new javax.swing.JMenuItem();

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenu1.setText("Agencias");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuAgenciasIncluir.setText("Incluir");
        jMenuAgenciasIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgenciasIncluirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAgenciasIncluir);

        jMenuAgenciasAlterar.setText("Alterar");
        jMenuAgenciasAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgenciasAlterarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAgenciasAlterar);

        jMenuAgenciasExcluir.setText("Excluir");
        jMenuAgenciasExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgenciasExcluirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAgenciasExcluir);

        jMenuAgenciasConsultar.setText("Consultar");
        jMenuAgenciasConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAgenciasConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAgenciasConsultar);

        jMenuBar1.add(jMenu1);

        jMenuClientes.setText("Clientes");

        jMenuClientesIncluir.setText("Incluir");
        jMenuClientesIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesIncluirActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuClientesIncluir);

        jMenuClientesAlterar.setText("Alterar");
        jMenuClientesAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesAlterarActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuClientesAlterar);

        jMenuClientesExcluir.setText("Excluir");
        jMenuClientesExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesExcluirActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuClientesExcluir);

        jMenuClientesConsultar.setText("Consultar");
        jMenuClientesConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesConsultarActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuClientesConsultar);

        jMenuBar1.add(jMenuClientes);

        jMenu3.setText("Conta Corrente");

        jMenuContaCorrenteIncluir.setText("Incluir");
        jMenuContaCorrenteIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContaCorrenteIncluirActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuContaCorrenteIncluir);

        jMenuContaCorrenteAlterar.setText("Alterar");
        jMenuContaCorrenteAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContaCorrenteAlterarActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuContaCorrenteAlterar);

        jMenuContaCorrenteExcluir.setText("Excluir");
        jMenuContaCorrenteExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContaCorrenteExcluirActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuContaCorrenteExcluir);

        jMenuContaCorrenteConsultar.setText("Consultar");
        jMenuContaCorrenteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuContaCorrenteConsultarActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuContaCorrenteConsultar);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Histórico");

        jMenuHistoricoIncluir.setText("Incluir");
        jMenuHistoricoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistoricoIncluirActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuHistoricoIncluir);

        jMenuHistoricoAlterar.setText("Alterar");
        jMenuHistoricoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistoricoAlterarActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuHistoricoAlterar);

        jMenuHistoricoExcluir.setText("Excluir");
        jMenuHistoricoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistoricoExcluirActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuHistoricoExcluir);

        jMenuHistoricoConsultar.setText("Consultar");
        jMenuHistoricoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistoricoConsultarActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuHistoricoConsultar);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Usuários");

        jMenuUsuariosIncluir.setText("Incluir");
        jMenuUsuariosIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosIncluirActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuUsuariosIncluir);

        jMenuUsuariosAlterar.setText("Alterar");
        jMenuUsuariosAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosAlterarActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuUsuariosAlterar);

        jMenuUsuariosExcluir.setText("Excluir");
        jMenuUsuariosExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosExcluirActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuUsuariosExcluir);

        jMenuUsuariosConsultar.setText("Consultar");
        jMenuUsuariosConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosConsultarActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuUsuariosConsultar);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Extrato de Movimentação");

        jMenuExtratoMovimentacaoIncluir.setText("Incluir");
        jMenuExtratoMovimentacaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExtratoMovimentacaoIncluirActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuExtratoMovimentacaoIncluir);

        jMenuExtratoMovimentacaoAlterar.setText("Alterar");
        jMenuExtratoMovimentacaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExtratoMovimentacaoAlterarActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuExtratoMovimentacaoAlterar);

        jMenuExtratoMovimentacaoExcluir.setText("Excluir");
        jMenuExtratoMovimentacaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExtratoMovimentacaoExcluirActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuExtratoMovimentacaoExcluir);

        jMenuExtratoMovimentacaoConsultar.setText("Consultar");
        jMenuExtratoMovimentacaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExtratoMovimentacaoConsultarActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuExtratoMovimentacaoConsultar);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuAgenciasIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgenciasIncluirActionPerformed
        // Cadastrar Agencias
        String acesso = "INCLUIR";
        ViewAgencias tela = new ViewAgencias(acesso);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuAgenciasIncluirActionPerformed

    private void jMenuContaCorrenteIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContaCorrenteIncluirActionPerformed
        // Cadastrar ContaCorrente
        String acesso = "INCLUIR";
        ViewContaCorrente tela = new ViewContaCorrente(acesso);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuContaCorrenteIncluirActionPerformed

    private void jMenuHistoricoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistoricoIncluirActionPerformed
        // Cadastrar Historico
        String operacao = "INCLUIR";
        ViewHistorico tela = new ViewHistorico(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuHistoricoIncluirActionPerformed

    private void jMenuUsuariosIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosIncluirActionPerformed
        // Cadastrar Usuario
        String operacao = "INCLUIR";
        ViewUsuarios tela = new ViewUsuarios(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuUsuariosIncluirActionPerformed

    private void jMenuExtratoMovimentacaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExtratoMovimentacaoIncluirActionPerformed
        // Cadastrar Extrato Movimentacao
        String operacao = "INCLUIR";
        ViewExtratoMovimentacao tela = new ViewExtratoMovimentacao(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuExtratoMovimentacaoIncluirActionPerformed

    private void jMenuClientesIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesIncluirActionPerformed
        // Cadastrar Cliente
        String operacao = "INCLUIR";
        ViewClientes tela = new ViewClientes(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuClientesIncluirActionPerformed

    private void jMenuClientesAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesAlterarActionPerformed
        // Alterar Cliente
        String operacao = "PesquisarAlterar";
        ViewClientes tela = new ViewClientes(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuClientesAlterarActionPerformed

    private void jMenuClientesExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesExcluirActionPerformed
        // Excluir Cliente
        String operacao = "PesquisarExcluir";
        ViewClientes tela = new ViewClientes(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuClientesExcluirActionPerformed

    private void jMenuClientesConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesConsultarActionPerformed
        // Consultar Clientes
        String operacao = "CONSULTAR";
        ViewClientesTabela tela = new ViewClientesTabela(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuClientesConsultarActionPerformed

    private void jMenuContaCorrenteAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContaCorrenteAlterarActionPerformed
        // Alterar Conta Corrente
        String operacao = "PesquisarAlterar";
        ViewContaCorrente tela = new ViewContaCorrente(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuContaCorrenteAlterarActionPerformed

    private void jMenuContaCorrenteExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContaCorrenteExcluirActionPerformed
        // Excluir Conta Corrente
        String operacao = "PesquisarExcluir";
        ViewContaCorrente tela = new ViewContaCorrente(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuContaCorrenteExcluirActionPerformed

    private void jMenuContaCorrenteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuContaCorrenteConsultarActionPerformed
        // Consultar Conta Corrente
        String operacao = "CONSULTAR";
        ViewContaCorrenteTabela tela = new ViewContaCorrenteTabela(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuContaCorrenteConsultarActionPerformed

    private void jMenuAgenciasConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgenciasConsultarActionPerformed
        // Consultar Agencias
        String operacao = "CONSULTAR";
        ViewAgencias tela = new ViewAgencias(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuAgenciasConsultarActionPerformed

    private void jMenuAgenciasAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgenciasAlterarActionPerformed
        // Alterar Agencias
        String operacao = "PesquisarAlterar";
        ViewAgencias tela = new ViewAgencias(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuAgenciasAlterarActionPerformed

    private void jMenuAgenciasExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAgenciasExcluirActionPerformed
        // Excluir Agencias
        String operacao = "PesquisarExcluir";
        ViewAgencias tela = new ViewAgencias(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuAgenciasExcluirActionPerformed

    private void jMenuHistoricoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistoricoAlterarActionPerformed
        // Alterar Historico
        String operacao = "PesquisarAlterar";
        ViewHistorico tela = new ViewHistorico(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuHistoricoAlterarActionPerformed

    private void jMenuHistoricoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistoricoExcluirActionPerformed
        // Excluir Historico
        String operacao = "PesquisarExcluir";
        ViewHistorico tela = new ViewHistorico(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuHistoricoExcluirActionPerformed

    private void jMenuHistoricoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistoricoConsultarActionPerformed
        // Consultar Historico
        String operacao = "CONSULTAR";
        ViewHistoricoTabela tela = new ViewHistoricoTabela(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuHistoricoConsultarActionPerformed

    private void jMenuUsuariosConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosConsultarActionPerformed
        // Consultar Usuario
        String operacao = "CONSULTAR";
        ViewUsuarios tela = new ViewUsuarios(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuUsuariosConsultarActionPerformed

    private void jMenuUsuariosAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosAlterarActionPerformed
        // Alterar Usuario
        String operacao = "PesquisaAlterar";
        ViewUsuarios tela = new ViewUsuarios(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuUsuariosAlterarActionPerformed

    private void jMenuUsuariosExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosExcluirActionPerformed
        // Excluir Usuario
        String operacao = "PesquisaExcluir";
        ViewUsuarios tela = new ViewUsuarios(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuUsuariosExcluirActionPerformed

    private void jMenuExtratoMovimentacaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExtratoMovimentacaoAlterarActionPerformed
        // Alterar Extrato Movimentacao
        String operacao = "PesquisaAlterar";
        ViewExtratoMovimentacao tela= new ViewExtratoMovimentacao(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuExtratoMovimentacaoAlterarActionPerformed

    private void jMenuExtratoMovimentacaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExtratoMovimentacaoExcluirActionPerformed
        // Excluir Extrato Movimentacao
        String operacao = "PesquisaExcluir";
        ViewExtratoMovimentacao tela = new ViewExtratoMovimentacao(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuExtratoMovimentacaoExcluirActionPerformed

    private void jMenuExtratoMovimentacaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExtratoMovimentacaoConsultarActionPerformed
        // Consultar Extrato Movimentacao
        String operacao = "CONSULTAR";
        ViewExtratoMovimentacao tela = new ViewExtratoMovimentacao(operacao);
        tela.setVisible(true);
    }//GEN-LAST:event_jMenuExtratoMovimentacaoConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuAgenciasAlterar;
    private javax.swing.JMenuItem jMenuAgenciasConsultar;
    private javax.swing.JMenuItem jMenuAgenciasExcluir;
    private javax.swing.JMenuItem jMenuAgenciasIncluir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenuItem jMenuClientesAlterar;
    private javax.swing.JMenuItem jMenuClientesConsultar;
    private javax.swing.JMenuItem jMenuClientesExcluir;
    private javax.swing.JMenuItem jMenuClientesIncluir;
    private javax.swing.JMenuItem jMenuContaCorrenteAlterar;
    private javax.swing.JMenuItem jMenuContaCorrenteConsultar;
    private javax.swing.JMenuItem jMenuContaCorrenteExcluir;
    private javax.swing.JMenuItem jMenuContaCorrenteIncluir;
    private javax.swing.JMenuItem jMenuExtratoMovimentacaoAlterar;
    private javax.swing.JMenuItem jMenuExtratoMovimentacaoConsultar;
    private javax.swing.JMenuItem jMenuExtratoMovimentacaoExcluir;
    private javax.swing.JMenuItem jMenuExtratoMovimentacaoIncluir;
    private javax.swing.JMenuItem jMenuHistoricoAlterar;
    private javax.swing.JMenuItem jMenuHistoricoConsultar;
    private javax.swing.JMenuItem jMenuHistoricoExcluir;
    private javax.swing.JMenuItem jMenuHistoricoIncluir;
    private javax.swing.JMenuItem jMenuUsuariosAlterar;
    private javax.swing.JMenuItem jMenuUsuariosConsultar;
    private javax.swing.JMenuItem jMenuUsuariosExcluir;
    private javax.swing.JMenuItem jMenuUsuariosIncluir;
    // End of variables declaration//GEN-END:variables
}
