/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import CLASSES.Historico;
import DAO.HistoricoDAO;
import javax.swing.JOptionPane;

/**
 * @author Ryan Carlo Negretti Pereira
 */
public class ViewHistorico extends javax.swing.JFrame {

    /**
     * Creates new form Historico
     */
    public ViewHistorico() {
        initComponents();
    }

    String operacaoAtivaGlobal = "NENHUM";

    private void limparCampos() {
        jTextFieldID.setText(" ");
        jTextFieldDescricao.setText(" ");
    }

    private void camposON() {
        jLabelDescricao.setVisible(true);
        jTextFieldDescricao.setVisible(true);
    }

    private void camposOFF() {
        jLabelDescricao.setVisible(false);
        jTextFieldDescricao.setVisible(false);
    }

    public ViewHistorico(String operacaoAtiva) {
        initComponents();
        operacaoAtivaGlobal = operacaoAtiva;
        String operacao = "INCLUIR";
        if (operacaoAtiva.equals(operacao)) {
            jLabelID.setVisible(true);
            jTextFieldID.setVisible(true);
            camposON();
            jButtonCadastrar.setVisible(true);
            jButtonLimpar.setVisible(true);
            jButtonExcluir.setVisible(false);
            jButtonConsultar.setVisible(false);
            jButtonAlterar.setVisible(false);
        }
        operacao = "PesquisarAlterar";
        if (operacaoAtiva.equals(operacao)) {
            jLabelID.setVisible(true);
            jTextFieldID.setVisible(true);
            camposOFF();
            jButtonCadastrar.setVisible(false);
            jButtonLimpar.setVisible(true);
            jButtonExcluir.setVisible(false);
            jButtonConsultar.setVisible(true);
            jButtonAlterar.setVisible(false);
        }
        operacao = "PesquisarExcluir";
        if (operacaoAtiva.equals(operacao)) {
            jLabelID.setVisible(true);
            jTextFieldID.setVisible(true);
            camposOFF();
            jButtonCadastrar.setVisible(false);
            jButtonLimpar.setVisible(true);
            jButtonExcluir.setVisible(false);
            jButtonConsultar.setVisible(true);
            jButtonAlterar.setVisible(false);
        }
    }

    Historico historico_tela = new Historico();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonConsultar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelID.setText("ID: ");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabelDescricao.setText("DESCRICAO:");

        jTextFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescricaoActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("CADASTRAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("LIMPAR");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonConsultar.setText("CONSULTAR");
        jButtonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("EXCLUIR");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("ALTERAR");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDescricao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDescricao))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescricao)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonConsultar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAlterar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescricaoActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        //CADASTRAR
        String operacao = "INCLUIR";
        if (operacaoAtivaGlobal.equals(operacao)) {
            Historico dados_historico = new Historico();
            dados_historico.setId(Integer.parseInt(jTextFieldID.getText()));
            dados_historico.setDescricao(jTextFieldDescricao.getText());

            HistoricoDAO objcon = new HistoricoDAO();

            objcon.insereRegistroJFBD("HISTORICOS", dados_historico.dadosSQLValues());

            limparCampos();
            dispose();
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        //LIMPAR CAMPOS
        limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarActionPerformed
        //BUSCAR DADOS
        String operacao = "PesquisarAlterar";
        if (operacaoAtivaGlobal.equals((operacao))) {
            HistoricoDAO objcon = new HistoricoDAO();
            Historico dados_historico;
            dados_historico = objcon.pesquisaRegistroJFDB("HISTORICOS", "ID = '"
                    + jTextFieldID.getText() + "'");

            if (dados_historico != null) {
                // Preencher os campos da tela com os dados do cliente
                jTextFieldID.setText(String.valueOf(dados_historico.getId()));
                jTextFieldDescricao.setText(dados_historico.getDescricao());

                camposON();
                jButtonCadastrar.setVisible(false);
                jButtonLimpar.setVisible(true);
                jButtonExcluir.setVisible(false);
                jButtonConsultar.setVisible(true);
                jButtonAlterar.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Historico não encontrado.");
            }
        }
        operacao = "PesquisarExcluir";
        if (operacaoAtivaGlobal.equals((operacao))) {
            HistoricoDAO objcon = new HistoricoDAO();
            Historico dados_historico;
            dados_historico = objcon.pesquisaRegistroJFDB("HISTORICOS", "ID = '"
                    + jTextFieldID.getText() + "'");

            if (dados_historico != null) {
                // Preencher os campos da tela com os dados do cliente
                jTextFieldID.setText(String.valueOf(dados_historico.getId()));
                jTextFieldDescricao.setText(dados_historico.getDescricao());

                camposON();
                jButtonCadastrar.setVisible(false);
                jButtonLimpar.setVisible(true);
                jButtonExcluir.setVisible(true);
                jButtonConsultar.setVisible(true);
                jButtonAlterar.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Historico não encontrado.");
            }
        }
    }//GEN-LAST:event_jButtonConsultarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        //EXCLUIR
        HistoricoDAO objcon = new HistoricoDAO();
        Historico dados_historico;
        dados_historico = objcon.pesquisaRegistroJFDB("HISTORICOS", "ID = '"
                + jTextFieldID.getText() + "'");

        jTextFieldID.setText(String.valueOf(dados_historico.getId()));
        jTextFieldDescricao.setText(dados_historico.getDescricao());

        objcon.excluirRegistroJFDB("HISTORICOS", "ID = '"
                + jTextFieldID.getText() + "'");

        limparCampos();
        dispose();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        //ALTERAR
        HistoricoDAO objcon = new HistoricoDAO();
        Historico dados_historico;
        dados_historico = objcon.pesquisaRegistroJFDB("HISTORICOS", "ID = '"
                + jTextFieldID.getText() + "'");

        dados_historico.setId(Integer.parseInt(jTextFieldID.getText()));
        dados_historico.setDescricao(jTextFieldDescricao.getText());
        try {
            objcon.alteraRegistroJFDB("HISTORICOS", dados_historico.alteraDadosSQLValues(),
                    "ID ='" + jTextFieldID.getText() + "'");
            limparCampos();
            dispose();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Não foi possível alterar. erro: " + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHistorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
